### ISSUE TITLE
No ready on fail

### ISSUE THREAD

**Issue by EloFran** [mylastore/svelte-boilerplate#1]
hi,
before install _npm i_ , and type _npm run dev_ , it return:

`$ sapper dev
• server
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\profile\index.svelte
A11y: Screenreaders already announce <img> elements as an image.
160:               <figure class="image is-4by3">
161:                 {#if currentUser.avatar}
162:                   <img
                       ^
163:                       class="default-img"
164:                       src={currentUser.avatar}
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\profile\index.svelte
A11y: Screenreaders already announce <img> elements as an image.
165:                       alt="User Image"/>
166:                 {:else}
167:                   <img
                       ^
168:                       class="default-img"
169:                       src='img/default-image.jpg'
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\profile\index.svelte
A11y: A form label must be associated with a control.
242:               <div class="field is-horizontal">
243:                 <div class="field-label">
244:                   <label class="label">Gender</label>
                       ^
245:                 </div>
246:                 <div class="field-body">
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
92:                     <p class="card-header-title">Events</p>
93:                     <a
94:                         href="#"
                            ^
95:                         class="card-header-icon"
96:                         aria-label="more options">
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
112:                             <a
113:                                 class="button is-small is-primary"
114:                                 href="#">
                                     ^
115:                               Action
116:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
125:                             <a
126:                                 class="button is-small is-primary"
127:                                 href="#">
                                     ^
128:                               Action
129:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
138:                             <a
139:                                 class="button is-small is-primary"
140:                                 href="#">
                                     ^
141:                               Action
142:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
151:                             <a
152:                                 class="button is-small is-primary"
153:                                 href="#">
                                     ^
154:                               Action
155:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
164:                             <a
165:                                 class="button is-small is-primary"
166:                                 href="#">
                                     ^
167:                               Action
168:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
177:                             <a
178:                                 class="button is-small is-primary"
179:                                 href="#">
                                     ^
180:                               Action
181:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
190:                             <a
191:                                 class="button is-small is-primary"
192:                                 href="#">
                                     ^
193:                               Action
194:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
203:                             <a
204:                                 class="button is-small is-primary"
205:                                 href="#">
                                     ^
206:                               Action
207:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
216:                             <a
217:                                 class="button is-small is-primary"
218:                                 href="#">
                                     ^
219:                               Action
220:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
226:                   </div>
227:                   <footer class="card-footer">
228:                     <a href="#" class="card-footer-item">View All</a>
                            ^
229:                   </footer>
230:                 </div>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
235:                     <p class="card-header-title">Inventory Search</p>
236:                     <a
237:                         href="#"
                             ^
238:                         class="card-header-icon"
239:                         aria-label="more options">
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
264:                     <p class="card-header-title">User Search</p>
265:                     <a
266:                         href="#"
                             ^
267:                         class="card-header-icon"
268:                         aria-label="more options">
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\settings.svelte
A11y: A form label must be associated with a control.
84:           <form class="form">
85:             <div class="no-margin">
86:               <label class="label">Email Notifications:</label>
                  ^
87:               <p class="help">
88:                An email will be sent to notify you base on the selections below.
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\users\[p([0-9]+)].svelte
A11y: Screenreaders already announce <img> elements as an image.
142:                   <td>
143:                     {#if user.avatar}
144:                       <img class="default-img" src={user.avatar} alt="User Image"/>
                           ^
145:                     {:else}
146:                       <img class="default-img" src="img/default-image.jpg" alt="User Image"/>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\users\[p([0-9]+)].svelte
A11y: Screenreaders already announce <img> elements as an image.
144:                       <img class="default-img" src={user.avatar} alt="User Image"/>
145:                     {:else}
146:                       <img class="default-img" src="img/default-image.jpg" alt="User Image"/>
                           ^
147:                     {/if}
148:                   </td>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\user\[id].svelte
A11y: Screenreaders already announce <img> elements as an image.
77:       {#if userWebsite}<p><b>Website: </b> <span>{userWebsite}</span></p>{/if}
78:       <br>
79:       <img class="center" src={userAvatar} alt="user image"/>
          ^
80:     </div>
81:   </div>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\components\Nav.svelte
A11y: <a> element should have an href attribute
39:                 {companyName}
40:             </a>
41:             <a role="button" class="navbar-burger burger {isActive ? 'is-active' : undefined}"
                ^
42:                on:click|stopPropagation|preventDefault={toggleNav} aria-label="menu" aria-expanded="false"      
43:                data-target="navMenu">
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\components\Nav.svelte
A11y: <a> element should have an href attribute
56:                 {#if $session.user}
57:                     <div class="navbar-item has-dropdown is-hoverable">
58:                         <a class="navbar-link">
                            ^
59:                             {#if $session.user.name}
60:                                 {$session.user.name}
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\components\Nav.svelte
A11y: <a> element should have an href attribute
76:                             </a>
77:                             <hr class="navbar-divider">
78:                             <a class="navbar-item" on:click|preventDefault={logOut}>
                                ^
79:                                 Logout
80:                             </a>
• client
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\register\index.svelte
Unused CSS selector ".la-google-btn"
164:   }
165:
166:   .la-google-btn {
       ^
167:     border: 2px solid #e6e7f0;
168:     line-height: 1;
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\register\index.svelte
Unused CSS selector ".la-google-btn span"
169:   }
170:
171:   .la-google-btn span {
       ^
172:     margin-right: 30px;
173:   }
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\profile\index.svelte
A11y: Screenreaders already announce <img> elements as an image.
160:               <figure class="image is-4by3">
161:                 {#if currentUser.avatar}
162:                   <img
                       ^
163:                       class="default-img"
164:                       src={currentUser.avatar}
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\profile\index.svelte
A11y: Screenreaders already announce <img> elements as an image.
165:                       alt="User Image"/>
166:                 {:else}
167:                   <img
                       ^
168:                       class="default-img"
169:                       src='img/default-image.jpg'
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\profile\index.svelte
A11y: A form label must be associated with a control.
242:               <div class="field is-horizontal">
243:                 <div class="field-label">
244:                   <label class="label">Gender</label>
                       ^
245:                 </div>
246:                 <div class="field-body">
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
92:                     <p class="card-header-title">Events</p>
93:                     <a
94:                         href="#"
                            ^
95:                         class="card-header-icon"
96:                         aria-label="more options">
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
112:                             <a
113:                                 class="button is-small is-primary"
114:                                 href="#">
                                     ^
115:                               Action
116:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
125:                             <a
126:                                 class="button is-small is-primary"
127:                                 href="#">
                                     ^
128:                               Action
129:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
138:                             <a
139:                                 class="button is-small is-primary"
140:                                 href="#">
                                     ^
141:                               Action
142:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
151:                             <a
152:                                 class="button is-small is-primary"
153:                                 href="#">
                                     ^
154:                               Action
155:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
164:                             <a
165:                                 class="button is-small is-primary"
166:                                 href="#">
                                     ^
167:                               Action
168:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
177:                             <a
178:                                 class="button is-small is-primary"
179:                                 href="#">
                                     ^
180:                               Action
181:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
190:                             <a
191:                                 class="button is-small is-primary"
192:                                 href="#">
                                     ^
193:                               Action
194:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
203:                             <a
204:                                 class="button is-small is-primary"
205:                                 href="#">
                                     ^
206:                               Action
207:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
216:                             <a
217:                                 class="button is-small is-primary"
218:                                 href="#">
                                     ^
219:                               Action
220:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
226:                   </div>
227:                   <footer class="card-footer">
228:                     <a href="#" class="card-footer-item">View All</a>
                            ^
229:                   </footer>
230:                 </div>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
235:                     <p class="card-header-title">Inventory Search</p>
236:                     <a
237:                         href="#"
                             ^
238:                         class="card-header-icon"
239:                         aria-label="more options">
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\index.svelte
A11y: '#' is not a valid href attribute
264:                     <p class="card-header-title">User Search</p>
265:                     <a
266:                         href="#"
                             ^
267:                         class="card-header-icon"
268:                         aria-label="more options">
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\settings.svelte
A11y: A form label must be associated with a control.
84:           <form class="form">
85:             <div class="no-margin">
86:               <label class="label">Email Notifications:</label>
                  ^
87:               <p class="help">
88:                An email will be sent to notify you base on the selections below.
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\login\index.svelte
Unused CSS selector ".la-google-btn"
187:   }
188:
189:   .la-google-btn {
       ^
190:     border: 2px solid #e6e7f0;
191:     line-height: 1;
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\login\index.svelte
Unused CSS selector ".la-google-btn span"
192:   }
193:
194:   .la-google-btn span {
       ^
195:     margin-right: 30px;
196:   }
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\user\[id].svelte
A11y: Screenreaders already announce <img> elements as an image.
77:       {#if userWebsite}<p><b>Website: </b> <span>{userWebsite}</span></p>{/if}
78:       <br>
79:       <img class="center" src={userAvatar} alt="user image"/>
          ^
80:     </div>
81:   </div>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\users\[p([0-9]+)].svelte
A11y: Screenreaders already announce <img> elements as an image.
142:                   <td>
143:                     {#if user.avatar}
144:                       <img class="default-img" src={user.avatar} alt="User Image"/>
                           ^
145:                     {:else}
146:                       <img class="default-img" src="img/default-image.jpg" alt="User Image"/>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\users\[p([0-9]+)].svelte
A11y: Screenreaders already announce <img> elements as an image.
144:                       <img class="default-img" src={user.avatar} alt="User Image"/>
145:                     {:else}
146:                       <img class="default-img" src="img/default-image.jpg" alt="User Image"/>
                           ^
147:                     {/if}
148:                   </td>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\routes\admin\users\[p([0-9]+)].svelte
Unused CSS selector "li.active a"
178:
179: <style>
180:   li.active a {
       ^
181:     color: #00818b;
182:   }
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\components\Nav.svelte
A11y: <a> element should have an href attribute
39:                 {companyName}
40:             </a>
41:             <a role="button" class="navbar-burger burger {isActive ? 'is-active' : undefined}"
                ^
42:                on:click|stopPropagation|preventDefault={toggleNav} aria-label="menu" aria-expanded="false"      
43:                data-target="navMenu">
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\components\Nav.svelte
A11y: <a> element should have an href attribute
56:                 {#if $session.user}
57:                     <div class="navbar-item has-dropdown is-hoverable">
58:                         <a class="navbar-link">
                            ^
59:                             {#if $session.user.name}
60:                                 {$session.user.name}
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\components\Nav.svelte
A11y: <a> element should have an href attribute
76:                             </a>
77:                             <hr class="navbar-divider">
78:                             <a class="navbar-item" on:click|preventDefault={logOut}>
                                ^
79:                                 Logout
80:                             </a>
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\components\Home.svelte
Unused CSS selector ".spacer"
266:
267: <style>
268:     .spacer{
         ^
269:         display: block;
270:         width: 100%;
E:\SVELTE Y FWORK7\SVELTE\Mi Store\svelte-boilerplate-master\src\components\paginate\PaginationNav.svelte
Unused CSS selector ".ellipsis"
84:
85: <style>
86:   .ellipsis{
      ^
87:     cursor: not-allowed;
88:     pointer-events: none;
✔ service worker (32ms)
Thu, 08 Oct 2020 18:02:31 GMT express-session deprecated req.secret; provide secret option at __sapper__\dev\server\server.js:4893:9
> Listening on http://localhost:3000`

**Comment by mylastore** [comment]
Despues de `npm i ` y despues `npm run dev ` eso paso?

**Comment by mylastore** [comment]
A si ya veo todos esos son warnings de svelte pero la applicasion funciona bien. Svelte muestra todos esos mesanges por que por ejemplo una imagen necesitan un `alt="some title"` pero solo te esta arvirtiendo que lo correcto es poner esa informacion.  Pero voy a tratar de quitar todos eso warnings y vuelvo a subir la applicasion ok. Gracias .

**Comment by mylastore** [comment]
Ok, ya quite todas las arventensias :) baja de nuevo y as `npm i `y `npm run dev `
