### ISSUE TITLE
Sigue sin funcionarme

### ISSUE THREAD

**Issue by EloFran** [mylastore/svelte-boilerplate#2]
Hola, 
Me sigue mostrando los mismo warning y además cuando accedo al localhost:3000 me dice:

_secret option required for sessions_

y no veo nada más.
Gracias.

**Comment by mylastore** [comment]
Tienes que bajar de nuevo la aplicación y lo de el mensaje tienes que cambiar el  nombre de el file example.env to .env y después agrega tus propios settings en ese file

**Comment by mylastore** [comment]
tienes rason de los warning nose por que no se subio los cambios

**Comment by mylastore** [comment]
ok ya lo ise update buelve a vajar y `npm i npm run dev `y cambia el nombre de `example.env` to `.env`
