### ISSUE TITLE
Login on live app not working

### ISSUE THREAD

**Issue by CherryDT** [mylastore/svelte-boilerplate#3]
When trying to log in to the live app, it takes a long time (with no loading indication by the way!) and then fails due to a 503 error on the backend.

![image](https://user-images.githubusercontent.com/6010463/99542498-73e16180-29b2-11eb-820f-e36c3739dcad.png)

**Comment by mylastore** [comment]
I improve the backend API added new features one is a multi user blog, but I will fixed the login and registration ASAP. Thanks

**Comment by mylastore** [comment]
Finally! ... example website is running again ;)
